<?php

namespace Database\Seeders;

use App\Models\TimeCategory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TimeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
        $time_categories=[
            [
                'name'=>'30минтан',
                'time'=>
                [
                    [
                        'start_time'=>'09:00',
                        'end_time'=>'09:30'
                    ],
                    [
                        'start_time'=>'09:30',
                        'end_time'=>'10:00'
                    ],
                    [
                        'start_time'=>'10:00',
                        'end_time'=>'10:30'
                    ],
                    [
                        'start_time'=>'10:30',
                        'end_time'=>'11:00'
                    ],
                    [
                        'start_time'=>'11:00',
                        'end_time'=>'11:30'
                    ],
                    [
                        'start_time'=>'11:30',
                        'end_time'=>'12:00'
                    ],
                    [
                        'start_time'=>'12:00',
                        'end_time'=>'12:30'
                    ],
                    [
                        'start_time'=>'12:30',
                        'end_time'=>'13:00'
                    ],
                    [
                        'start_time'=>'14:00',
                        'end_time'=>'14:30'
                    ],
                    [
                        'start_time'=>'14:30',
                        'end_time'=>'15:00'
                    ],
                    [
                        'start_time'=>'15:00',
                        'end_time'=>'15:30'
                    ],
                    [
                        'start_time'=>'15:30',
                        'end_time'=>'16:00'
                    ],
                    [
                        'start_time'=>'16:00',
                        'end_time'=>'16:30'
                    ],
                    [
                        'start_time'=>'16:30',
                        'end_time'=>'17:00'
                    ]
                ]
            ],
            [
                'name'=>'20минтан',
                'time'=>[
                    [
                        'start_time'=>'09:00',
                        'end_time'=>'09:20'
                    ],
                    [
                        'start_time'=>'09:20',
                        'end_time'=>'09:40'
                    ],
                    [
                        'start_time'=>'09:40',
                        'end_time'=>'10:00'
                    ],
                    [
                        'start_time'=>'10:00',
                        'end_time'=>'10:20'
                    ],
                    [
                        'start_time'=>'10:20',
                        'end_time'=>'10:40'
                    ],
                    [
                        'start_time'=>'10:40',
                        'end_time'=>'11:00'
                    ],
                    [
                        'start_time'=>'11:00',
                        'end_time'=>'11:20'
                    ],
                    [
                        'start_time'=>'11:20',
                        'end_time'=>'11:40'
                    ],
                    [
                        'start_time'=>'11:40',
                        'end_time'=>'12:00'
                    ],
                    [
                        'start_time'=>'12:00',
                        'end_time'=>'12:20'
                    ],
                    [
                        'start_time'=>'12:20',
                        'end_time'=>'12:40'
                    ],
                    [
                        'start_time'=>'12:40',
                        'end_time'=>'13:00'
                    ],
                    [
                        'start_time'=>'14:00',
                        'end_time'=>'14:20'
                    ],
                    [
                        'start_time'=>'14:20',
                        'end_time'=>'14:40'
                    ],
                    [
                        'start_time'=>'14:40',
                        'end_time'=>'15:00'
                    ],
                    [
                        'start_time'=>'15:00',
                        'end_time'=>'15:20'
                    ],
                    [
                        'start_time'=>'15:20',
                        'end_time'=>'15:40'
                    ],
                    [
                        'start_time'=>'15:40',
                        'end_time'=>'16:00'
                    ],
                    [
                        'start_time'=>'16:00',
                        'end_time'=>'16:20'
                    ],
                    [
                        'start_time'=>'16:20',
                        'end_time'=>'16:40'
                    ],
                    [
                        'start_time'=>'16:40',
                        'end_time'=>'17:00'
                    ]
                ]
            ],

        ];

        foreach ($time_categories as $category) {
            TimeCategory::create([
                'name'=>$category['name'],
            ]);
            $time_category=TimeCategory::where('name',$category['name'])->first();
            foreach ($category['time'] as $time) {
                $time_category->times()->create([
                    'start_time'=>$time['start_time'],
                    'end_time'=>$time['end_time']
                ]);
            }
        }
    }
}
